### ISSUE TITLE
🚀 I would like To have (each server) a sub domain like quad9.country code.blahdns.com/..

### ISSUE THREAD

**Issue by BirdInFire** [zoonderkins/blahdns#211]
**Is your feature request related to a problem?**
I would like to add more security on my resolution.

**Describe the solution you'd like**
Add a facultative subdomain to use resolver who is configured to ask quad9 and their 18+ list of bad actor, like quad9.countrycodeoftheserver.blahdns.com.

**Describe alternatives you've considered**
None.

**Additional context**
This feature will reduce the load of the local resolver, ans enhance security for those who want it.

**Comment by ookangzheng** [comment]
So will be like 
user --> Germany server --> quad9 ?

**Comment by BirdInFire** [comment]
yes (with the addition of ads-filterlist of course).
It permit to let choice for user, and help the local resolver (since he seem overcharged some time (see in your post https://github.com/ookangzheng/blahdns/issues/36)) so double win, this let the one who want quad9 have it, and these user by using this will reduce the charge of the local resolver for the user who want this local resolver.

**Comment by BirdInFire** [comment]
Warning : this kind of server will not support anymore other type of domain for instance : OpenNIC support | Ethereum Name Service by default, but only do a warning under the config and go on :)
