### ISSUE TITLE
Question about dns over quic protocol

### ISSUE THREAD

**Issue by Techguyprivate** [zoonderkins/blahdns#22]
Sorry for the question. I didn't find any mention over whteher blahdns works over QUIC as google dns does.

Thank you.

**Comment by ookangzheng** [comment]
Hi
I look up to QUIC a little bit, as far I know there is no common tool or software support QUIC yet, just Google. and also it will Google's QUIC is different from IETF standard. 
Anyway, It is good to have a look at it. If Golang DNS library supports QUIC protocol, then I think I will try to do a prototype version of it. 

References: 
1. https://daniel.haxx.se/blog/tag/quic
2. https://github.com/lucas-clemente/quic-go
