### ISSUE TITLE
🐛  Unable to check if BlahDNS is used by my system becuase test.blahdns.com SSL certificate is expired

### ISSUE THREAD

**Issue by Galang23** [zoonderkins/blahdns#288]
**Checklist**

- [X] I read the [README](https://github.com/ookangzheng/blahdns/blob/master/README.md)
- [X] I read the [FAQ](https://github.com/ookangzheng/blahdns/blob/master/FAQ.md)
- [X] I searched the [issues](https://github.com/ookangzheng/blahdns/issues?q=is%3Aissue+)

**Describe the issue**
Unable to check if BlahDNS is used by my system becuase test.blahdns.com SSL certificate is expired 3 months ago (2023-03-08).

**To Reproduce**

1. Open BlahDNS.com
2. See "You are not using Blahdns !!!"
3. Open Devtools
4. Go to Network tab
5. See that test.blahdns.com is not accessed due to SEC_ERROR_EXPIRED_CERTIFICATE
6. Opening test.blahdns.com further confirms the error.

**Expected behaviours**
1. https://test.blahdns.com's SSL certificate should be up to date (valid);
2. BlahDNS.com should show BlahDNS DNS Server used on client.

**Screenshots**
Below is current blahdns.com website when accessed using blahdns DoH SG server.
![Screenshot 2023-06-24 at 02-42-55 Blahdns -- a hobby adblock DNS resolver support HTTP_3 DoH DoT DoQ DNSCryptv2](https://github.com/zoonderkins/blahdns/assets/13700948/39b9659b-6083-40a1-8338-d00bcff4ac0f)

Below is Devtools Network Tab showing test.blahdns.com
![firefox_SRjnzn6LUh](https://github.com/zoonderkins/blahdns/assets/13700948/4bd30951-e674-4fbb-8750-9569a221e9e0)

Below is the error page shown when accessing https://test.blahdns.com (per 2023-06-24 02:42 UTC+7)
![The error page](https://github.com/zoonderkins/blahdns/assets/13700948/5f2f1cbf-2465-4b92-8644-02143bfa756f)

**Client:**
- Device: Windows
- OS: Windows 10
- Client: Firefox
- Protocol: DoH

**Comment by zoonderkins** [comment]
Done ~
