### ISSUE TITLE
Unable to Access Amazon Prime Video App with Blahdns on Android TV 

### ISSUE THREAD

**Issue by mstflgz** [zoonderkins/blahdns#293]
Dear Blahdns Developers,

I hope this message finds you well. I am a Blahdns user on my Android TV, and I am experiencing a significant issue with the Amazon Prime Video app. The app does not open for hours, making it entirely unusable while Blahdns is active.

While I value the privacy and security that Blahdns provides, I also depend on streaming services such as Amazon Prime Video for my entertainment needs. Unfortunately, I am currently unable to access any content through the app due to the extensive delays in loading and usability issues.

I wanted to bring this serious problem to your attention, as it affects my overall experience as a user. I kindly request your assistance in investigating and resolving this issue promptly. It would be greatly appreciated if you could provide guidance or solutions to ensure that Blahdns can be used without hindering the functionality of Amazon Prime Video.

Thank you for your dedication to maintaining a secure and private DNS service. I eagerly await your response and assistance in resolving this pressing matter.

Sincerely,

**Comment by zoonderkins** [comment]
Still not working?
