### ISSUE TITLE
🐛 Cert error in server for Japan

### ISSUE THREAD

**Issue by yutayu** [zoonderkins/blahdns#295]
**Checklist**

- [x ] I read the [README](https://github.com/ookangzheng/blahdns/blob/master/README.md)
- [ x] I read the [FAQ](https://github.com/ookangzheng/blahdns/blob/master/FAQ.md)
- [ x] I searched the [issues](https://github.com/ookangzheng/blahdns/issues?q=is%3Aissue+)

**Describe the issue**
A clear and concise description of what the issue is.
Cert error in server for Japan. both ipv6 and ipv4.
**To Reproduce**

1. ...set blahdns in toml file 
2. ...start dnscrypt-proxy

**Expected behavior**

**Logs (optional)**
If applicable, add logs or screenshots to help explain your problem.

If you can reproduce the issue, please describe it below.

**Server if applicable):**

- OS: [e.g. Debian 10]
- Hosting provider (if applicable): [e.g. Vultr, AWS, OpenWRT, RaspberryPI]

**Client (if applicable):**

- Device: [e.g. iPhone, Android, Linux, Windows]
- OS: [e.g. iOS13, Android 10, Debian 10, Windows 10]
- Client: [e.g. Nebulo, Unbound, Bind9, Dnscrypt-v2, Intra]
- Protocol: [e.g. DoH, DoT, Dnscrypt]

**Additional context**

**Comment by yutayu** [comment]
I only check dnscrypt server.

**Comment by zoonderkins** [comment]
Where did you get dnscrypt server information?

```
Provider name: 2.dnscrypt-cert.blahdns.com
Provider public key: d4c2c9594dbecf2a0d21ed5c5b43b4981574d05ae2543cd2e3cef119f7471ca1

## IPv4
Public server address: 212.52.0.233:8443
DNS Stamp: sdns://AQMAAAAAAAAAETIxMi41Mi4wLjIzMzo4NDQzINTCyVlNvs8qDSHtXFtDtJgVdNBa4lQ80uPO8Rn3RxyhGzIuZG5zY3J5cHQtY2VydC5ibGFoZG5zLmNvbQ

## IPv6
Public server address: [2406:ef80:4:1537::1]:8443
DNS Stamp: sdns://AQMAAAAAAAAAGlsyNDA2OmVmODA6NDoxNTM3OjoxXTo4NDQzINTCyVlNvs8qDSHtXFtDtJgVdNBa4lQ80uPO8Rn3RxyhGzIuZG5zY3J5cHQtY2VydC5ibGFoZG5zLmNvbQ
```

**Comment by yutayu** [comment]
Very sorry. 
Both servers work fine , now.

**Comment by yutayu** [comment]
https://blahdns.com/

DNSCrypt v2
IPv4 - DNSStamp:sdns://AQMAAAAAAAAAETIxMi41Mi4wLjIzMzo4NDQzIIUTqWvE4INLlQ1jtQLo0-LVTQSWayYCkzTpBx26I_wrGzIuZG5zY3J5cHQtY2VydC5ibGFoZG5zLmNvbQ

IPv6 - DNSStamp:sdns://AQMAAAAAAAAAJVsyNDAwOjg5MDI6OmYwM2M6OTJmZjpmZTI3OjM0NGJdOjg0NDMghROpa8Tgg0uVDWO1AujT4tVNBJZrJgKTNOkHHboj_CsbMi5kbnNjcnlwdC1jZXJ0LmJsYWhkbnMuY29t

This doesn't work. and It is different from yours.
What you typed above works :)
