### ISSUE TITLE
🐛 Error of blocklist for unbound.

### ISSUE THREAD

**Issue by yutayu** [zoonderkins/blahdns#296]
**Checklist**

- [ x] I read the [README](https://github.com/ookangzheng/blahdns/blob/master/README.md)
- [ x] I read the [FAQ](https://github.com/ookangzheng/blahdns/blob/master/FAQ.md)
- [x ] I searched the [issues](https://github.com/ookangzheng/blahdns/issues?q=is%3Aissue+)

**Describe the issue**
A clear and concise description of what the issue is.
blocklist syntax error in unbound

/etc/unbound/conf.d/blahdns_unbound.conf:8: error: syntax error
read /etc/unbound/unbound.conf failed: 1 errors in configuration file

**To Reproduce**

1. ...let unbound read blocklist for unbound
2. ...

**Expected behavior**

**Logs (optional)**
If applicable, add logs or screenshots to help explain your problem.

If you can reproduce the issue, please describe it below.

**Server if applicable):**

- OS: [e.g. Debian 10]
- Hosting provider (if applicable): [e.g. Vultr, AWS, OpenWRT, RaspberryPI]

**Client (if applicable):**

- Device: [e.g. iPhone, Android, Linux, Windows]
- OS: [e.g. iOS13, Android 10, Debian 10, Windows 10]
- Client: [e.g. Nebulo, Unbound, Bind9, Dnscrypt-v2, Intra]
- Protocol: [e.g. DoH, DoT, Dnscrypt]

**Additional context**

**Comment by zoonderkins** [comment]
Hi,
I've update the Unbound conf 
please try this out https://github.com/zoonderkins/blahdns/blob/master/client-conf/unbound.conf

**Comment by yutayu** [comment]
/etc/unbound/conf.d/blahdns_unbound.conf:8: error: syntax error
read /etc/unbound/unbound.conf failed: 1 errors in configuration file

I mean that 8th line of blocklist is bad.

**Comment by zoonderkins** [comment]
Can you paste it here the complete `conf`  
`/etc/unbound/conf.d/blahdns_unbound.conf`

**Comment by yutayu** [comment]
I reinstalled  OS and lost it.
Hold on.

**Comment by yutayu** [comment]
[Unbound](https://oooo.b-cdn.net/blahdns/blahdns_unbound.conf) 

https://github.com/zoonderkins/blahdns/blob/4a866af94b8df4624751fb65f050d60712f74699/hosts/README.md?plain=1#L2

/etc/unbound/unbound.conf.d/blahdns_unbound.conf:8: error: syntax error, is there no section start after an include-toplevel directive perhaps.
read /etc/unbound/unbound.conf failed: 1 errors in configuration file
[1713544291] unbound-control[26799:0] fatal error: could not read config file

**Comment by zoonderkins** [comment]
Maybe delete entire conf you copied from old README and replace only `forward-zone` instead.

```
    forward-zone:
        name: "."
        forward-tls-upstream: yes

        forward-addr: 212.52.0.233@853#dot-jp.blahdns.com
```

**Comment by yutayu** [comment]
I didn't notice readme is old.
I use blahdns through  dnscrypt and it works well.
Much Thanks :)
