### ISSUE TITLE
Germany public key is out of date.

### ISSUE THREAD

**Issue by LucioAmely** [zoonderkins/blahdns#299]
Germany server's public key provided in the DNSCrypt Stamp does not match the server's private key, thus invalidating the DNS Stamp. While connecting dnscrypt-proxy client gives the following error as in the #294.

`[WARNING] [dnscrypt-de-blahdns-ipv4] Incorrect signature for provider name: [2.dnscrypt-cert.blahdns.com.]`

Singapore server's DNSCrypt stamp is valid. This only happens in the Germany server right now. Please provide more up-to-date stamps.

Also I would like to thank you for your great services over the years. I would like to ask if there may be any possibility to re-open the Switzerland server in the near future?

**Comment by LucioAmely** [comment]
Also just noticed out, SG server's DNSCrypt stamp in the website is pointing out to the old IP address. The address found in the dnscrypt-proxy config file which can be found in this repo is alright.

**Comment by LucioAmely** [comment]
@zoonderkins

**Comment by zoonderkins** [comment]
Hi,

Let me check it out ~

**Comment by LucioAmely** [comment]
> Hi,
> 
> Let me check it out ~

Thank you for taking your time.

**Comment by zoonderkins** [comment]
Hi @LucioAmely 
Please try it again later. 
I submitted an update to DNSCrypt repo.
