### ISSUE TITLE
🚀 Add blocklist of famous quad9 dns

### ISSUE THREAD

**Issue by trimechee** [zoonderkins/blahdns#302]
Hi, it will be great to add blocklist of famous secure Quad9 dns to more security feeling safe please, or add other blocklists of famous secure dns that block malwares virus like blocklist of cira dns, dns0, nextdns, thank you :

https://raw.githubusercontent.com/AssoEchap/stalkerware-indicators/master/generated/quad9_blocklist.txt

**Comment by zoonderkins** [comment]
Hi,

The list is added to the server blocklist.
